import json

from graphplatform.ingestion.manifest.npm_lock import parse_npm_lockfile
from graphplatform.ingestion.manifest.python_lock import parse_poetry_lock, parse_requirements_txt

# -- package-lock.json v1 --------------------------------------------------

PACKAGE_LOCK_V1 = {
    "lockfileVersion": 1,
    "dependencies": {
        "lodash": {"version": "4.17.21"},
        "is-odd": {
            "version": "3.0.1",
            "dependencies": {
                "is-number": {"version": "6.0.0"},
                # a shadowed, differently-resolved copy nested deeper --
                # the shallower top-level "lodash" above must win.
                "lodash": {"version": "3.10.1"},
            },
        },
    },
}


def test_package_lock_v1_flattens_and_prefers_shallowest():
    resolved = parse_npm_lockfile("package-lock.json", json.dumps(PACKAGE_LOCK_V1))
    assert resolved == {"lodash": "4.17.21", "is-odd": "3.0.1", "is-number": "6.0.0"}


# -- package-lock.json v2/v3 ------------------------------------------------

PACKAGE_LOCK_V3 = {
    "lockfileVersion": 3,
    "packages": {
        "": {"name": "root"},
        "node_modules/lodash": {"version": "4.17.21"},
        "node_modules/is-odd": {"version": "3.0.1"},
        "node_modules/is-odd/node_modules/lodash": {"version": "3.10.1"},  # shadowed, deeper
        "node_modules/@scope/thing": {"version": "1.2.3"},
    },
}


def test_package_lock_v3_flattens_scoped_names_and_prefers_shallowest():
    resolved = parse_npm_lockfile("package-lock.json", json.dumps(PACKAGE_LOCK_V3))
    assert resolved["lodash"] == "4.17.21"
    assert resolved["is-odd"] == "3.0.1"
    assert resolved["@scope/thing"] == "1.2.3"


# -- yarn.lock (classic v1) --------------------------------------------------

YARN_LOCK_CLASSIC = """\
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"is-odd@^3.0.1":
  version "3.0.1"
  resolved "https://registry.yarnpkg.com/is-odd/-/is-odd-3.0.1.tgz"
  dependencies:
    is-number "^6.0.0"

"@scope/thing@^1.0.0", "@scope/thing@^1.2.0":
  version "1.2.3"
  resolved "https://registry.yarnpkg.com/@scope/thing/-/thing-1.2.3.tgz"

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
"""


def test_yarn_lock_classic_parses_scoped_and_unscoped_and_multi_descriptor_blocks():
    resolved = parse_npm_lockfile("yarn.lock", YARN_LOCK_CLASSIC)
    assert resolved == {
        "is-odd": "3.0.1",
        "@scope/thing": "1.2.3",
        "lodash": "4.17.21",
    }


YARN_LOCK_BERRY = """\
# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 6
  cacheKey: 8

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
"""


def test_yarn_lock_berry_is_detected_and_skipped_not_misparsed():
    resolved = parse_npm_lockfile("yarn.lock", YARN_LOCK_BERRY)
    assert resolved == {}


# -- pnpm-lock.yaml -----------------------------------------------------------

PNPM_LOCK_V6 = """\
lockfileVersion: '6.0'

packages:
  /lodash@4.17.21:
    resolution: {integrity: sha512-xxx}
  /is-odd@3.0.1:
    resolution: {integrity: sha512-xxx}
    dependencies:
      is-number: 6.0.0
  /@scope/thing@1.2.3:
    resolution: {integrity: sha512-xxx}
  /react-dom@18.2.0(react@18.2.0):
    resolution: {integrity: sha512-xxx}
"""


def test_pnpm_lock_parses_scoped_names_and_strips_peer_suffix():
    resolved = parse_npm_lockfile("pnpm-lock.yaml", PNPM_LOCK_V6)
    assert resolved["lodash"] == "4.17.21"
    assert resolved["is-odd"] == "3.0.1"
    assert resolved["@scope/thing"] == "1.2.3"
    assert resolved["react-dom"] == "18.2.0"


# -- poetry.lock --------------------------------------------------------------

POETRY_LOCK = """\
[[package]]
name = "requests"
version = "2.31.0"

[[package]]
name = "certifi"
version = "2024.2.2"
"""


def test_poetry_lock_parses_every_package_table():
    resolved = parse_poetry_lock(POETRY_LOCK)
    assert resolved == {"requests": "2.31.0", "certifi": "2024.2.2"}


# -- requirements.txt ----------------------------------------------------------

REQUIREMENTS_TXT = """\
# a comment
click==8.1.7
requests>=2.0
-e git+https://example.com/foo.git#egg=foo
flask[async]==3.0.0 ; python_version >= "3.8"
"""


def test_requirements_txt_keeps_only_exact_pins():
    resolved = parse_requirements_txt(REQUIREMENTS_TXT)
    assert resolved == {"click": "8.1.7", "flask": "3.0.0"}
